sonar.projectKey=Dental_CIS
sonar.projectName=Dental CIS
sonar.projectVersion=1.0

sonar.sources=client/src,server/src
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.host.url=http://192.168.101.45:9000

sonar.token=sqp_f578b9e5d8a869595f3fa4ed53d7f6626e2df074

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,server/prisma/**,server/legacy-bridge/**,client/dist/**,**/*.min.js

