export const WEB_SCREEN_META = {
  'about-us': { title: 'About Us', legacy: 'web_aboutus_v1.php', desc: 'Manage About Us CMS pages' },
  departments: { title: 'Departments', legacy: 'web_departments_v1.php', desc: 'Department pages' },
  lms: { title: 'LMS', legacy: 'web_lms_v1.php', desc: 'LMS content pages' },
  journal: { title: 'Journal', legacy: 'web_journal_v1.php', desc: 'Journal pages' },
  facilities: { title: 'Facilities', legacy: 'web_facilities_v1.php', desc: 'Facilities pages' },
  aaadar: { title: 'AAADAR', legacy: 'web_aaadar_v1.php', desc: 'AAADAR pages' },
  research: { title: 'Research', legacy: 'web_research_v1.php', desc: 'Research CMS pages' },
  academic: { title: 'Academic', legacy: 'web_academic_v1.php', desc: 'Academic pages' },
  iqac: { title: 'IQAC', legacy: 'web_iqac_v1.php', desc: 'IQAC pages' },
  outreach: { title: 'Outreach', legacy: 'web_out_reach_v1.php', desc: 'Outreach pages' },
  'slider-animation': { title: 'Slider Animation', legacy: 'home_slider_widget_edit.php', desc: 'Home page slider widgets' },
  'photos-add': { title: 'Photos — Add', legacy: 'photos_add.php', desc: 'Add photo gallery' },
  'photos-edit': { title: 'Photos — Edit', legacy: 'photos_edit.php', desc: 'Edit photo galleries' },
  'staff-display-order': { title: 'Staff Web Display Order', legacy: 'staff_web_display_order_setup.php', desc: 'Staff order on website by department' },
  'doc-upload': { title: 'Web Document Upload', legacy: 'website_doc_upload.php', desc: 'Upload PDF documents for the website' },
  'research-program-add': { title: 'Research Program — Add', legacy: 'web_research_news_add.php', desc: 'Add research program / news' },
  'research-program-edit': { title: 'Research Program — Edit', legacy: 'web_research_news_edit.php', desc: 'Edit research programs' },
  'event-add': { title: 'Events — Add', legacy: 'festival_event_add.php', desc: 'Add website events' },
  'event-edit': { title: 'Events — Edit', legacy: 'festival_event_edit.php', desc: 'Edit website events' },
  'event-type': { title: 'Event Type', legacy: 'event_category.php', desc: 'Event category master' },
};
