export const COMMITTEE_SCREEN_META = {
  dashboard: { title: 'Committee Dashboard', legacy: 'committee_dashboard.php' },
  'committee-report': { title: 'Committees Information', legacy: 'event_committee_report.php' },
  'committee-add': { title: 'Committee Add', legacy: 'event_committee_add.php' },
  'committee-edit': { title: 'Committee Edit', legacy: 'event_committee_edit.php' },
  'committee-member': { title: 'Manage Members', legacy: 'event_committee_member.php' },
  designation: { title: 'Designation', legacy: 'event_committee_designation.php' },
  'event-type': { title: 'Event Type', legacy: 'committee_event_type.php' },
  'task-category': { title: 'Task Category', legacy: 'task_category_setup.php' },
  'client-add': { title: 'Add Client', legacy: 't_client_add.php' },
  'client-edit': { title: 'Edit Client', legacy: 't_client_edit.php' },
  'task-colour': { title: 'Colour Setup', legacy: 'task_colour_setup.php' },
  'task-type': { title: 'Report Type', legacy: 'task_type_setup.php' },
  'task-wtype': { title: 'Work Type', legacy: 'task_wtype_setup.php' },
  'task-participator': { title: 'Participator', legacy: 'task_participator_setup.php' },
  'task-misc': { title: 'Miscellaneous', legacy: 'task_miscellaneous_setup.php' },
  'task-doc-type': { title: 'Document Type', legacy: 'task_document_type.php' },
  'task-time-sheet': { title: 'Time Sheet', legacy: 'task_time_sheet_setup.php' },
  'task-budget-expenses': { title: 'Budget Expenses', legacy: 'task_budget_expenses.php' },
  'task-event-org': { title: 'Partners/Sponsors', legacy: 'task_event_organization.php' },
  'task-dashboard': { title: 'Task Dashboard', legacy: 'st_task_dashboard.php' },
  'task-allocation': { title: 'Manage Task', legacy: 'st_task_allocation_approved.php', initialLoadFields: { tab: 'open' } },
  'task-allocation-v2': { title: 'Manage Task V2', legacy: 'st_task_allocation_approved_v2.php', initialLoadFields: { tab: 'open' } },
  'task-manage-report': { title: 'Task Report', legacy: 'task_manage_report.php', initialLoadFields: { eventStatus: '1', taskStatus: 'Open' } },
  'task-document': { title: 'Task Documents', legacy: 'task_document.php' },
  'task-budget-approved': { title: 'Budget Approved', legacy: 'task_budget_approved.php' },
  'approve-event': { title: 'Approve Event', legacy: 'approve_event.php' },
  'approve-event-report': { title: 'Approve Event Report', legacy: 'approve_event_report.php' },
  'approve-reschedule': { title: 'Reschedule Approval', legacy: 'approve_reschedule_event_v1.php' },
  'tv-academic-event': { title: 'Academic Event Calendar', legacy: 'tv_academic_event.php' },
  'tv-academic-print': { title: 'Academic Event Print', legacy: 'tv_academic_print.php' },
};
