export const TV_SLIDE_EFFECTS = [
  { group: 'BASICS', options: [
    { value: 'notransition', label: 'No Transition' },
    { value: 'fade', label: 'Fade' },
    { value: 'crossfade', label: 'Fade Cross' },
    { value: 'fadethroughdark', label: 'Fade Through Black' },
    { value: 'fadethroughlight', label: 'Fade Through Light' },
    { value: 'fadethroughtransparent', label: 'Fade Through Transparent' },
  ]},
  { group: 'SLIDE SIMPLE', options: [
    { value: 'slideup', label: 'Slide To Top' },
    { value: 'slidedown', label: 'Slide To Bottom' },
    { value: 'slideright', label: 'Slide To Right' },
    { value: 'slideleft', label: 'Slide To Left' },
    { value: 'slidehorizontal', label: 'Slide Horizontal (Next/Previous)' },
    { value: 'slidevertical', label: 'Slide Vertical (Next/Previous)' },
  ]},
  { group: 'SLIDE OVER', options: [
    { value: 'slideoverup', label: 'Slide Over To Top' },
    { value: 'slideoverdown', label: 'Slide Over To Bottom' },
    { value: 'slideoverright', label: 'Slide Over To Right' },
    { value: 'slideoverleft', label: 'Slide Over To Left' },
    { value: 'slideoverhorizontal', label: 'Slide Over Horizontal (Next/Previous)' },
    { value: 'slideoververtical', label: 'Slide Over Vertical (Next/Previous)' },
  ]},
  { group: 'SLIDE REMOVE', options: [
    { value: 'slideremoveup', label: 'Slide Remove To Top' },
    { value: 'slideremovedown', label: 'Slide Remove To Bottom' },
    { value: 'slideremoveright', label: 'Slide Remove To Right' },
    { value: 'slideremoveleft', label: 'Slide Remove To Left' },
    { value: 'slideremovehorizontal', label: 'Slide Remove Horizontal (Next/Previous)' },
    { value: 'slideremovevertical', label: 'Slide Remove Vertical (Next/Previous)' },
  ]},
  { group: 'SLIDING OVERLAYS', options: [
    { value: 'slidingoverlayup', label: 'Sliding Overlays To Top' },
    { value: 'slidingoverlaydown', label: 'Sliding Overlays To Bottom' },
    { value: 'slidingoverlayright', label: 'Sliding Overlays To Right' },
    { value: 'slidingoverlayleft', label: 'Sliding Overlays To Left' },
    { value: 'slidingoverlayhorizontal', label: 'Sliding Overlays Horizontal (Next/Previous)' },
    { value: 'slidingoverlayvertical', label: 'Sliding Overlays Vertical (Next/Previous)' },
  ]},
  { group: 'SLOTS AND BOXES', options: [
    { value: 'boxslide', label: 'Slide Boxes' },
    { value: 'slotslide-horizontal', label: 'Slide Slots Horizontal' },
    { value: 'slotslide-vertical', label: 'Slide Slots Vertical' },
    { value: 'boxfade', label: 'Fade Boxes' },
    { value: 'slotfade-horizontal', label: 'Fade Slots Horizontal' },
    { value: 'slotfade-vertical', label: 'Fade Slots Vertical' },
  ]},
  { group: 'FADE & SLIDE', options: [
    { value: 'fadefromright', label: 'Fade and Slide from Right' },
    { value: 'fadefromleft', label: 'Fade and Slide from Left' },
    { value: 'fadefromtop', label: 'Fade and Slide from Top' },
    { value: 'fadefrombottom', label: 'Fade and Slide from Bottom' },
    { value: 'fadetoleftfadefromright', label: 'To Left From Right' },
    { value: 'fadetorightfadefromleft', label: 'To Right From Left' },
    { value: 'fadetotopfadefrombottom', label: 'To Top From Bottom' },
    { value: 'fadetobottomfadefromtop', label: 'To Bottom From Top' },
  ]},
  { group: 'PARALLAX', options: [
    { value: 'parallaxtoright', label: 'Parallax to Right' },
    { value: 'parallaxtoleft', label: 'Parallax to Left' },
    { value: 'parallaxtotop', label: 'Parallax to Top' },
    { value: 'parallaxtobottom', label: 'Parallax to Bottom' },
    { value: 'parallaxhorizontal', label: 'Parallax Horizontal' },
    { value: 'parallaxvertical', label: 'Parallax Vertical' },
  ]},
  { group: 'ZOOM TRANSITIONS', options: [
    { value: 'scaledownfromright', label: 'Zoom Out and Fade From Right' },
    { value: 'scaledownfromleft', label: 'Zoom Out and Fade From Left' },
    { value: 'scaledownfromtop', label: 'Zoom Out and Fade From Top' },
    { value: 'scaledownfrombottom', label: 'Zoom Out and Fade From Bottom' },
    { value: 'zoomout', label: 'ZoomOut' },
    { value: 'zoomin', label: 'ZoomIn' },
    { value: 'slotzoom-horizontal', label: 'Zoom Slots Horizontal' },
    { value: 'slotzoom-vertical', label: 'Zoom Slots Vertical' },
  ]},
  { group: 'CURTAIN TRANSITIONS', options: [
    { value: 'curtain-1', label: 'Curtain from Left' },
    { value: 'curtain-2', label: 'Curtain from Right' },
    { value: 'curtain-3', label: 'Curtain from Middle' },
  ]},
  { group: 'FILTER TRANSITIONS', options: [
    { value: 'grayscale', label: 'Grayscale Transition' },
    { value: 'grayscalecross', label: 'Grayscale Cross Transition' },
    { value: 'brightness', label: 'Brightness Transition' },
    { value: 'brightnesscross', label: 'Brightness Cross Transition' },
    { value: 'blurlight', label: 'Blur Light Transition' },
    { value: 'blurlightcross', label: 'Blur Light Cross Transition' },
    { value: 'blurstrong', label: 'Blur Strong Transition' },
    { value: 'blurstrongcross', label: 'Blur Strong Cross Transition' },
  ]},
  { group: 'PREMIUM TRANSITIONS', options: [
    { value: '3dcurtain-horizontal', label: '3D Curtain Horizontal' },
    { value: '3dcurtain-vertical', label: '3D Curtain Vertical' },
    { value: 'cube', label: 'Cube Vertical' },
    { value: 'cube-horizontal', label: 'Cube Horizontal' },
    { value: 'incube', label: 'In Cube Vertical' },
    { value: 'incube-horizontal', label: 'In Cube Horizontal' },
    { value: 'turnoff', label: 'TurnOff Horizontal' },
    { value: 'turnoff-vertical', label: 'TurnOff Vertical' },
    { value: 'papercut', label: 'Paper Cut' },
    { value: 'flyin', label: 'Fly In' },
  ]},
  { group: 'RANDOM', options: [
    { value: 'random-selected', label: 'Random of Selected' },
    { value: 'random-static', label: 'Random Flat' },
    { value: 'random-premium', label: 'Random Premium' },
    { value: 'random', label: 'Random Flat and Premium' },
  ]},
];

export function flattenSlideEffects() {
  return TV_SLIDE_EFFECTS.flatMap((g) => g.options);
}
