import { prisma } from '../../config/prisma.js';
import { escapeSql } from '../../utils/sqlSafe.js';
import {
  appendPayrollReportSignature,
  buildCategoryFilter,
  formatIndianMoney,
  formatPayrollMonthLabel,
  getStaffOrderClause,
  loadDesignationMap,
  loadPrintSetup,
} from './payrollHelpers.js';

import {
  buildArrearReportHtml,
  buildEsiReportHtml,
  buildLoanReportHtml,
  buildLopReportHtml,
  buildMessReportHtml,
  buildPfReportHtml,
  buildRentalReportHtml,
  buildTdsReportHtml,
  buildTransportReportHtml,
} from './payrollDeductionReportCore.js';

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function staffDisplayName(row) {
  const title = row.staff_title ? `${String(row.staff_title).trim()}. ` : '';
  return `${title}${String(row.staff_name || '').trim()} ${String(row.staff_initial || '').trim()}`.trim();
}

const REPORT_SIGN_SETUP = {
  bank: '5',
  rental: '6',
  mess: '7',
  pf: '8',
  esi: '9',
  lop_amount: '10',
  lop_detail: '19',
  arrear_amount: '11',
  loan_amount: '12',
  other_deduction: '14',
  tds_amount: '13',
  prof_tax: '15',
  advance_amount: '18',
  transport_deduction: '193',
  security_deposit: '192',
  sdeposit_refund: '194',
  gross_pay: '195',
};

export { REPORT_SIGN_SETUP };

const SIMPLE_AMOUNT_REPORTS = new Set([
  'lop_amount', 'arrear_amount', 'loan_amount', 'other_deduction',
  'tds_amount', 'prof_tax', 'advance_amount', 'transport_deduction',
  'security_deposit', 'sdeposit_refund', 'gross_pay',
]);

export async function buildDashboardReportHtml(payrollMonth, categoryFilterSql, generatedBy) {
  const printSetup = await loadPrintSetup('1');
  const totals = await prisma.$queryRawUnsafe(
    `SELECT
       SUM(B.net_pay) AS net_pay,
       SUM(B.gross_pay) AS gross_pay,
       SUM(B.lop_amount) AS lop_amount,
       SUM(B.arrear_amount) AS arrear_amount,
       SUM(B.pf_amount) AS pf_amount,
       SUM(B.esi_amount) AS esi_amount,
       SUM(B.rental_amount) AS rental_amount,
       SUM(B.hostel_amount) AS hostel_amount,
       SUM(B.tds_amount) AS tds_amount,
       SUM(B.prof_tax) AS prof_tax,
       SUM(B.other_deduction) AS other_deduction,
       SUM(B.loan_amount) AS loan_amount
     FROM staff_profile_tb AS A
     INNER JOIN staff_payroll_tb AS B ON A.id = B.staff_id
     WHERE A.del = 1 AND B.del = 1
       AND B.payroll_month = '${escapeSql(payrollMonth)}'
       ${categoryFilterSql}`,
  );
  const t = totals[0] || {};
  const netPay = Number(t.net_pay) || 0;
  const liabilities = (Number(t.pf_amount) || 0) + (Number(t.esi_amount) || 0)
    + (Number(t.rental_amount) || 0) + (Number(t.hostel_amount) || 0)
    + (Number(t.tds_amount) || 0) + (Number(t.prof_tax) || 0)
    + (Number(t.other_deduction) || 0) + (Number(t.loan_amount) || 0);
  const totalCtc = netPay + liabilities;

  const bankSummary = await prisma.$queryRawUnsafe(
    `SELECT SUM(B.net_pay) AS amount
     FROM staff_profile_tb AS A
     INNER JOIN staff_payroll_tb AS B ON A.id = B.staff_id
     WHERE A.del = 1 AND B.del = 1 AND B.net_pay > 0
       AND B.payroll_month = '${escapeSql(payrollMonth)}'
       ${categoryFilterSql}`,
  );
  const bankTotal = Number(bankSummary[0]?.amount) || 0;

  const genLabel = generatedBy?.user
    ? `<p class="text-muted small">Generated by ${escapeHtml(generatedBy.user)} on ${escapeHtml(generatedBy.date || '')}</p>`
    : '';

  return appendPayrollReportSignature(`${genLabel}
<p class="header1">Payroll Dashboard &nbsp;</p>
<table class="table-bordered" cellpadding="2" cellspacing="0">
<tr bgcolor="#7f7f7f">
<td height="45" valign="middle" class="text-center pd_header" nowrap>1. Pay Checks</td>
<td valign="middle" class="text-center pd_header" nowrap>2. Pay Liabilities</td>
<td valign="middle" class="text-center pd_header" nowrap>Total</td>
<td valign="middle" class="text-center pd_header" nowrap>3. Reference</td>
</tr>
<tr>
<td rowspan="2" valign="top" class="text-center" width="180" bgcolor="#f3f3f3">
<p class="pd_header_1">${formatIndianMoney(netPay)}</p>
<p class="pd_content_1">Total Payable</p>
</td>
<td rowspan="2" valign="top" class="text-center" width="180" bgcolor="#e6e6e6">
<p class="pd_header_1">${formatIndianMoney(liabilities)}</p>
<p class="pd_content_1">Tax &amp; Non-Tax Payments</p>
</td>
<td rowspan="2" valign="top" class="text-center" width="180" bgcolor="#cecece">
<p class="pd_header_1">${formatIndianMoney(totalCtc)}</p>
<p class="pd_content_1">Total Employee CTC</p>
</td>
<td valign="top" height="45" class="text-center" width="180">
<p class="pd_header_2">${formatIndianMoney(t.lop_amount)}</p>
<p class="pd_content_2">LOP</p>
</td>
</tr>
<tr>
<td valign="top" height="45" class="text-center">
<p class="pd_header_2">${formatIndianMoney(t.arrear_amount)}</p>
<p class="pd_content_2">Arrear</p>
</td>
</tr>
</table>
<p class="pd_content_1">Bank / cheque payout: ${formatIndianMoney(bankTotal)} (${formatPayrollMonthLabel(payrollMonth)})</p>`, printSetup);
}

export async function buildIndividualReportHtml(options) {
  const {
    payrollMonth,
    categoryFilterSql,
    reportFor,
    rowPerPage = 27,
    copyType = 'Original Copy',
    generatedBy,
    transferRef = '',
  } = options;

  const signId = REPORT_SIGN_SETUP[reportFor] || REPORT_SIGN_SETUP.gross_pay;
  const [printSetup, designationMap, orderClause] = await Promise.all([
    loadPrintSetup(signId),
    loadDesignationMap(),
    getStaffOrderClause(),
  ]);
  const monthSql = escapeSql(payrollMonth);
  const copySuffix = copyType ? ` (${copyType})` : '';
  const reportCtx = {
    payrollMonth,
    monthSql,
    categoryFilterSql,
    orderClause,
    printSetup,
    copySuffix,
    generatedBy,
    designationMap,
    rowPerPage,
  };

  if (reportFor === 'bank') {
    const bankHtml = await buildBankReport({ ...reportCtx, transferRef });
    return bankHtml ? appendPayrollReportSignature(bankHtml, printSetup) : '';
  }

  if (reportFor === 'pf') {
    const html = await buildPfReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }
  if (reportFor === 'esi') {
    const html = await buildEsiReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }
  if (reportFor === 'rental') {
    const html = await buildRentalReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }
  if (reportFor === 'mess') {
    const html = await buildMessReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }
  if (reportFor === 'lop_amount') {
    const html = await buildLopReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }
  if (reportFor === 'arrear_amount') {
    const html = await buildArrearReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }
  if (reportFor === 'loan_amount') {
    const html = await buildLoanReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }
  if (reportFor === 'tds_amount') {
    const html = await buildTdsReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }
  if (reportFor === 'transport_deduction') {
    const html = await buildTransportReportHtml(reportCtx);
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }

  if (SIMPLE_AMOUNT_REPORTS.has(reportFor)) {
    const html = await buildSimpleAmountReport({
      payrollMonth,
      monthSql,
      categoryFilterSql,
      orderClause,
      printSetup,
      copySuffix,
      generatedBy,
      reportFor,
      rowPerPage,
      designationMap,
    });
    return html ? appendPayrollReportSignature(html, printSetup) : '';
  }

  return '';
}

async function buildBankReport(ctx) {
  const bankFilter = ctx.transferRef === 'cheque'
    ? " AND B.pay_type = 'Cheque'"
    : (ctx.transferRef ? ` AND B.pay_type != 'Cheque' AND B.pay_bank = '${escapeSql(ctx.transferRef)}'` : '');

  const rows = await prisma.$queryRawUnsafe(
    `SELECT A.staff_id, A.staff_title, A.staff_name, A.staff_initial,
            B.net_pay, B.pay_type, A.mobile_1, A.b_ifsc, A.email_id, A.b_ac_no
     FROM staff_profile_tb AS A
     INNER JOIN staff_payroll_tb AS B ON A.id = B.staff_id
     WHERE A.del = 1 AND B.del = 1 AND B.net_pay > 0
       AND B.payroll_month = '${ctx.monthSql}'
       ${ctx.categoryFilterSql}
       ${bankFilter}
     ${ctx.orderClause}`,
  );

  if (!rows.length) return '';

  let body = `<p class="header1">${escapeHtml(ctx.printSetup.body_title || 'Bank Payment')}</p>
<table class="table-bordered" cellpadding="3" cellspacing="0">
<thead><tr bgcolor="#e7e7e7">
<th>#</th><th>S.ID</th><th>Amount (Rs)</th><th>Name</th><th>A/C No.</th><th>Mail Id</th><th>IFSC</th><th>Mobile</th>
</tr></thead><tbody>`;

  let total = 0;
  rows.forEach((row, idx) => {
    const amount = Number(row.net_pay) || 0;
    total += amount;
    body += `<tr>
<td>${idx + 1}</td>
<td nowrap>${escapeHtml(row.staff_id)}</td>
<td class="text-right">${formatIndianMoney(amount)}</td>
<td nowrap>${escapeHtml(staffDisplayName(row))}</td>
<td nowrap>${escapeHtml(row.pay_type === 'Cheque' ? row.pay_type : row.b_ac_no)}</td>
<td nowrap>${escapeHtml(row.email_id)}</td>
<td nowrap>${escapeHtml(row.b_ifsc)}</td>
<td nowrap>${escapeHtml(row.mobile_1)}</td>
</tr>`;
  });

  body += `</tbody><tfoot><tr bgcolor="#f4f4f4">
<td colspan="2" class="text-right"><strong>Total</strong></td>
<td class="text-right"><strong>${formatIndianMoney(total)}</strong></td>
<td colspan="5"></td>
</tr></tfoot></table>
<p class="text-muted small">Generated by ${escapeHtml(ctx.generatedBy?.user || '')} on ${escapeHtml(ctx.generatedBy?.date || '')}</p>`;
  return body;
}

async function buildSimpleAmountReport(ctx) {
  const column = ctx.reportFor;
  const designationMap = ctx.designationMap || {};
  const rows = await prisma.$queryRawUnsafe(
    `SELECT A.staff_id, A.staff_title, A.staff_name, A.staff_initial, B.designation, B.${column} AS amount
     FROM staff_profile_tb AS A
     INNER JOIN staff_payroll_tb AS B ON A.id = B.staff_id
     WHERE A.del = 1 AND B.del = 1 AND B.${column} > 0
       AND B.payroll_month = '${ctx.monthSql}'
       ${ctx.categoryFilterSql}
     ${ctx.orderClause}`,
  );

  if (!rows.length) return '';

  const title = ctx.printSetup.body_title || column.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  let body = `<p class="header1">${escapeHtml(title)}${ctx.printSetup.body_title ? ' &nbsp;' : ` — ${formatPayrollMonthLabel(ctx.payrollMonth)}${escapeHtml(ctx.copySuffix)}`}</p>
<table class="table-bordered" cellpadding="3" cellspacing="0">
<thead><tr bgcolor="#e7e7e7">
<th>#</th><th>S.ID</th><th>Name</th><th>Designation</th><th>Amount (Rs)</th>
</tr></thead><tbody>`;

  let total = 0;
  rows.forEach((row, idx) => {
    const amount = Number(row.amount) || 0;
    total += amount;
    body += `<tr>
<td>${idx + 1}</td>
<td nowrap>${escapeHtml(row.staff_id)}</td>
<td nowrap>${escapeHtml(staffDisplayName(row))}</td>
<td nowrap>${escapeHtml(designationMap[row.designation] || '')}</td>
<td class="text-right">${formatIndianMoney(amount)}</td>
</tr>`;
  });

  body += `</tbody><tfoot><tr bgcolor="#f4f4f4">
<td colspan="4" class="text-right"><strong>Total</strong></td>
<td class="text-right"><strong>${formatIndianMoney(total)}</strong></td>
</tr></tfoot></table>`;
  return body;
}

export function normalizeReportFor(reportFor) {
  const raw = String(reportFor || '').trim();
  if (!raw) return 'gross_pay';
  if (raw.startsWith('bank_')) return 'bank';
  if (raw === 'bank_cheque') return 'bank';
  return raw;
}

export function parseBankTransferRef(reportFor) {
  const raw = String(reportFor || '');
  if (raw.startsWith('bank_')) return raw.slice(5);
  if (raw === 'bank_cheque') return 'cheque';
  return '';
}

export async function loadReportTypeOptions(payrollMonth) {
  if (!payrollMonth) return [];
  const monthSql = escapeSql(payrollMonth);
  const sums = await prisma.$queryRawUnsafe(
    `SELECT
       SUM(rental_amount) AS rental,
       SUM(hostel_amount) AS mess,
       SUM(pf_amount) AS pf,
       SUM(esi_amount) AS esi,
       SUM(lop_amount) AS lop_amount,
       SUM(arrear_amount) AS arrear_amount,
       SUM(loan_amount) AS loan_amount,
       SUM(tds_amount) AS tds_amount,
       SUM(prof_tax) AS prof_tax,
       SUM(other_deduction) AS other_deduction,
       SUM(advance_amount) AS advance_amount,
       SUM(security_deposit) AS security_deposit,
       SUM(transport_deduction) AS transport_deduction,
       SUM(sdeposit_refund) AS sdeposit_refund,
       SUM(gross_pay) AS gross_pay
     FROM staff_payroll_tb WHERE del = 1 AND payroll_month = '${monthSql}'`,
  );
  const s = sums[0] || {};

  const banks = await prisma.edu_setup_tb.findMany({
    where: { category: 'Bank', del: 1 },
    orderBy: { category_order: 'asc' },
  });

  const options = [];
  for (const bank of banks) {
    options.push({
      value: `bank_${bank.id}`,
      label: `${bank.category_sname || bank.category_name} Transfer`,
      visible: true,
    });
  }
  options.push({ value: 'bank_cheque', label: 'Cheque Payment', visible: true });

  const deductions = [
    ['rental', 'Rental'],
    ['mess', 'Mess'],
    ['pf', 'PF'],
    ['esi', 'ESI'],
    ['lop_amount', 'LOP'],
    ['lop_detail', 'LOP Detail'],
    ['arrear_amount', 'Arrear'],
    ['loan_amount', 'Loan'],
    ['tds_amount', 'TDS'],
    ['prof_tax', 'Professional Tax'],
    ['other_deduction', 'Other Deduction'],
    ['advance_amount', 'Advance'],
    ['security_deposit', 'Security Deposit'],
    ['transport_deduction', 'Transport Deduction'],
    ['sdeposit_refund', 'Security Deposit Refund'],
    ['gross_pay', 'Gross Pay'],
  ];

  for (const [key, label] of deductions) {
    options.push({
      value: key,
      label,
      visible: Number(s[key]) > 0,
    });
  }

  return options;
}

export { buildCategoryFilter };
