import { prisma } from '../../../config/prisma.js';
import { basicSetupCourseSelect } from '../../../utils/legacySelects.js';
import { escapeSql } from '../../../utils/sqlSafe.js';
import { parseInputDate } from '../../shared/ciaSetupHelpers.js';
import { convertNYear } from '../../fees/feeHelpers.js';
import { escapeHtml } from '../academicSetupShared.js';
import { logAcademicSetup } from '../setup/setupAudit.js';

const PAGE = 'timetable_class_report.php';

function batchLetters() {
  const map = {};
  let letter = 'A';
  for (let i = 1; i <= 26; i += 1) {
    map[i] = letter;
    letter = String.fromCharCode(letter.charCodeAt(0) + 1);
  }
  return map;
}

function formatPeriodTime(fromTime, toTime) {
  const fmt = (t) => {
    if (!t || String(t) === '00:00:00') return '';
    const d = new Date(`1970-01-01T${String(t).slice(0, 8)}`);
    return Number.isNaN(d.getTime()) ? '' : d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }).toLowerCase();
  };
  const from = fmt(fromTime);
  const to = fmt(toTime);
  return from && to ? `${from} - ${to}` : from || to || '';
}

function formatLegacyGeneratedAt(d = new Date()) {
  const datePart = d.toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  }).replace(',', '');
  const timePart = d.toLocaleString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  }).toLowerCase();
  return `${datePart} at ${timePart}`;
}

async function loadBannerImageUrl() {
  const rows = await prisma.$queryRawUnsafe(
    'SELECT banner_image FROM basic_banner_tb WHERE del = 1 AND id = 1 LIMIT 1',
  );
  const image = rows[0]?.banner_image;
  return image ? `/legacy/img/global_images/${encodeURIComponent(image)}` : '';
}

function buildPrintHeaderHtml(reportTitle, subtitleHtml, bannerUrl) {
  const logo = bannerUrl ? `<img src="${escapeHtml(bannerUrl)}" alt="" />` : '';
  return `<div id="printingHeader" style="display:none;">
<div id="printHeaderpanel" class="first-page">
<table class="header_table" border="0" cellpadding="0" cellspacing="0" width="100%"><tbody>
<tr><td align="center" height="5" colspan="2"><small>omsakthi</small></td></tr>
<tr>
<td height="70" valign="middle" width="30%">${logo}</td>
<td nowrap align="right" valign="top" width="70%"><div class="promote_card">
<p class="pc_title title">${escapeHtml(reportTitle)}</p>
<p class="pc_sub-title sub-title">${subtitleHtml}</p>
</div></td>
</tr>
</tbody></table>
</div>
</div>`;
}

function buildPrintFooterHtml(verticalText, memberId) {
  const generatedAt = formatLegacyGeneratedAt(new Date());
  const generatedBy = memberId
    ? `<p id="generated_by">Generated by ${escapeHtml(memberId)} on ${escapeHtml(generatedAt)}</p>`
    : '';
  return `<div id="printingFooter" style="display:none;">
<div id="printFooterpanel">
<div class="right_container"><div class="vertical_container">${escapeHtml(verticalText)}</div></div>
${generatedBy}
<table class="footer_table" border="0" cellpadding="0" cellspacing="0" width="100%"><tbody>
<tr>
<td nowrap valign="top" width="90%"><p class="footer_sign_note"></p></td>
<td height="40" align="right" valign="top" width="10%"><p id="print_page_no"></p></td>
</tr>
</tbody></table>
</div>
</div>`;
}

async function loadPeriodTime(courseName, currentYear, academicType, day, periodNo, cache) {
  const key = `${courseName}_${currentYear}_${academicType}_${day}_${periodNo}`;
  if (cache[key]) return cache[key];
  const dayFilter = ` AND (p_days='${escapeSql(day)}' OR p_days LIKE '${escapeSql(day)},%' OR p_days LIKE '%,${escapeSql(day)}' OR p_days LIKE '%,${escapeSql(day)},%')`;
  const rows = await prisma.$queryRawUnsafe(
    `SELECT CAST(from_time AS CHAR) AS from_time, CAST(to_time AS CHAR) AS to_time
     FROM period_set_up WHERE del != 0 AND period_no='${escapeSql(String(periodNo))}'
       AND course_name='${escapeSql(courseName)}' AND academic_year='${escapeSql(String(currentYear))}'
       AND academic_type='${escapeSql(academicType)}' ${dayFilter}
     ORDER BY period_no+0 ASC LIMIT 1`,
  );
  const time = formatPeriodTime(rows[0]?.from_time, rows[0]?.to_time);
  cache[key] = time;
  return time;
}

export async function loadTimetableReport(memberId, fields = {}, audit = {}) {
  const attendanceDate = String(fields.attendance_date || '').trim();
  const passType = fields.a_pass_type === 'Clinical' ? 'Clinical' : 'Theory';
  const generate = Boolean(fields.generate);
  let html = '';

  if (generate && attendanceDate) {
    const curDate = parseInputDate(attendanceDate);
    const day = new Date(curDate).toLocaleDateString('en-US', { weekday: 'long' }).toLowerCase();
    const catFilter = passType === 'Clinical' ? 'B.subject_category!=11' : 'B.subject_category=11';

    const courses = await prisma.basic_setup_course_tb.findMany({
      where: { del: 1 },
      select: basicSetupCourseSelect,
    });
    const courseById = Object.fromEntries(courses.map((c) => [c.id, c]));
    const degreeMap = Object.fromEntries(courses.map((c) => {
      let dept = String(c.department_short_name || '').trim();
      if (dept && dept !== '-') dept = ` - ${dept}`;
      return [c.id, `${c.degree_name}${dept}`];
    }));

    const roomRows = await prisma.$queryRawUnsafe(
      'SELECT R.id, R.room_name FROM rooms_tb AS R INNER JOIN blocks_tb AS B ON R.block_id=B.id WHERE R.del=1 AND B.del=1',
    );
    const roomMap = Object.fromEntries(roomRows.map((r) => [String(r.id), r.room_name]));

    const catRows = await prisma.$queryRawUnsafe(
      "SELECT id, category_name FROM subject_master WHERE del = 1 AND category = 'Timetable' ORDER BY category_order ASC",
    );
    const catMap = Object.fromEntries(catRows.map((r) => [String(r.id), r.category_name]));

    const rows = await prisma.$queryRawUnsafe(
      `SELECT DISTINCT A.subject_id, A.course_id, A.academic_year, A.current_year, A.academic_type,
              A.period, A.batch_no, A.staff_id, A.topic_id, A.id,
              B.subject_name, B.subject_category, B.room_no, B.s_batch
       FROM timetable_tb AS A
       INNER JOIN basic_subject_tt_tb AS B ON A.subject_id = B.id
       WHERE A.del=1 AND B.del=1 AND A.academic_type='regular'
         AND A.t_day='${escapeSql(day)}'
         AND CAST(A.from_date AS CHAR) <= '${escapeSql(curDate)}'
         AND CAST(A.from_date AS CHAR) != '0000-00-00'
         AND (CAST(A.to_date AS CHAR) >= '${escapeSql(curDate)}' OR CAST(A.to_date AS CHAR) = '0000-00-00')
         AND ${catFilter}
       ORDER BY A.course_id ASC, A.current_year ASC, A.period ASC`,
    );

    const staffRows = await prisma.$queryRawUnsafe(
      `SELECT A.id, A.staff_id, A.staff_title, A.staff_name, A.staff_initial
       FROM staff_profile_tb AS A
       INNER JOIN staff_designation_tb AS B ON A.id = B.staff_id
       WHERE A.del = 1 AND (A.releaving_date = '0000-00-00' OR A.releaving_date > '${escapeSql(curDate)}')
         AND B.del = 1 AND B.is_academic = 1 ORDER BY A.staff_id ASC`,
    );
    const staffMap = {};
    for (const s of staffRows) {
      const title = s.staff_title ? `${s.staff_title}.` : '';
      const label = [title, s.staff_initial, s.staff_name].filter(Boolean).join(' ').trim();
      staffMap[s.id] = `${s.staff_id} | ${label}`;
    }

    const topicRows = await prisma.$queryRawUnsafe(
      `SELECT C.id, U.name AS unit_name, C.name AS topic_name
       FROM basic_subject_unit AS U
       INNER JOIN basic_subject_chapter AS C ON U.id = C.u_id
       WHERE U.del = 1 AND C.del = 1`,
    );
    const topicMap = {};
    for (const t of topicRows) topicMap[t.id] = `${t.unit_name}-${t.topic_name}`;

    const subjectCache = {};
    const periodCache = {};
    const batchMap = batchLetters();
    const bannerUrl = await loadBannerImageUrl();
    const reportTitle = ' E-Learning';
    const subtitle = `${escapeHtml(curDate)} | ${escapeHtml(day)}`;
    const verticalText = `${reportTitle} | ${curDate} | ${day}`;

    let tableBody = '';
    for (let i = 0; i < rows.length; i += 1) {
      const row = rows[i];
      const course = courseById[Number(row.course_id)];
      const courseName = course?.course_name || '';
      const time = courseName
        ? await loadPeriodTime(courseName, row.current_year, row.academic_type || 'regular', day, row.period, periodCache)
        : '';

      const staffNames = String(row.staff_id || '').split(',')
        .map((id) => staffMap[Number(id.trim())] || staffMap[id.trim()] || '')
        .filter(Boolean);

      let batchLabel = '-';
      if (Number(row.s_batch) === 1) {
        const parts = String(row.batch_no || '').split(',').map((b) => batchMap[Number(b.trim())]).filter(Boolean);
        batchLabel = parts.length ? parts.join(', ') : '-';
      }

      if (!subjectCache[row.subject_id]) {
        subjectCache[row.subject_id] = {
          name: row.subject_name,
          cat: catMap[String(row.subject_category)] || '',
          room: roomMap[String(row.room_no)] || '',
        };
      }
      const subj = subjectCache[row.subject_id];
      const yearLabel = convertNYear(Number(row.current_year), courseName);
      const addSuffix = String(row.academic_type || '').toLowerCase() === 'additional' ? ' (Add.)' : '';
      const courseLabel = `${yearLabel} ${degreeMap[row.course_id] || ''}${addSuffix}`.trim();
      const rowBg = (i + 1) % 2 === 0 ? ' bgcolor="#f4f4f4"' : '';

      tableBody += `<tr${rowBg}>
<td nowrap valign="top">${i + 1}</td>
<td nowrap valign="top">${staffNames.map((name) => escapeHtml(name)).join('<br>')}</td>
<td height="35" align="center">${escapeHtml(String(row.period))}</td>
<td>${escapeHtml(time)}</td>
<td>${escapeHtml(courseLabel)}</td>
<td>${escapeHtml(batchLabel)}</td>
<td>${escapeHtml(subj.name)}</td>
<td>${escapeHtml(subj.cat)}</td>
<td>${escapeHtml(topicMap[row.topic_id] || '')}</td>
<td>${escapeHtml(subj.room)}</td>
</tr>`;
    }

    const tableHtml = `<div id="form_details_panel">
<table width="100%" border="0" cellpadding="5" cellspacing="0" class="table table-bordered timetable-class-report-table">
<thead>
<tr>
<th width="5%" height="35" nowrap>#</th>
<th width="10%" height="35" nowrap>Staff</th>
<th width="5%" align="center">Period</th>
<th width="15%" align="center">Time</th>
<th width="15%" align="center">Course</th>
<th width="5%" align="center">Batch</th>
<th width="15%" align="center">Subject</th>
<th width="10%" align="center">Type</th>
<th width="10%" align="center">Topic</th>
<th width="10%" align="center">Room</th>
</tr>
</thead>
<tbody>${tableBody}</tbody>
</table>
</div>`;

    html = `${buildPrintHeaderHtml(reportTitle, subtitle, bannerUrl)}${tableHtml}${buildPrintFooterHtml(verticalText, memberId)}`;
  }

  await logAcademicSetup(PAGE, 'View', 'Successful', attendanceDate, memberId, audit);
  return {
    attendanceDate,
    passType,
    html,
  };
}

export async function saveTimetableReport() {
  return { success: false, message: 'Report screen is read-only' };
}
