import { prisma } from '../../../../config/prisma.js';
import { escapeSql } from '../../../../utils/sqlSafe.js';
import { convertNYear } from '../../../fees/feeHelpers.js';
import { loadPrintSetup, loadPrintSignatureHtml } from '../../../payroll/payrollHelpers.js';
import { logAcademicSetup } from '../../setup/setupAudit.js';
import {
  escapeHtml,
  formatDateTime,
  loadFeedbackOptions,
} from './reportShared.js';

const PAGE = 'feedback_dashboard.php';
const FEEDBACK_PRINT_SETUP_ID = '17';

function formatFeedbackGeneratedAt(d = new Date()) {
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  const timePart = d.toLocaleString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  }).toLowerCase();
  return `${dd}-${mm}-${yyyy} at ${timePart}`;
}

async function loadBannerImageUrl() {
  const rows = await prisma.$queryRawUnsafe(
    'SELECT banner_image FROM basic_banner_tb WHERE del = 1 AND id = 1 LIMIT 1',
  );
  const image = rows[0]?.banner_image;
  return image ? `/legacy/img/global_images/${encodeURIComponent(image)}` : '';
}

function buildFeedbackPrintHeaderHtml(reportTitle, feedbackTitle, bannerUrl) {
  const logo = bannerUrl ? `<img src="${escapeHtml(bannerUrl)}" alt="" />` : '';
  return `<div id="printingHeader" style="display:none;">
<div id="printHeaderpanel" class="first-page">
<table class="header_table" border="0" cellpadding="0" cellspacing="0" width="100%"><tbody>
<tr><td align="center" height="5" colspan="2"><small>omsakthi</small></td></tr>
<tr>
<td height="70" valign="middle" width="30%">${logo}</td>
<td nowrap align="right" valign="top" width="70%"><div class="promote_card">
<p class="pc_title title">${escapeHtml(reportTitle)}</p>
<p class="pc_sub-title sub-title">${escapeHtml(feedbackTitle)}</p>
<div class="pc_sub-title-1 sub-title-1">Filled Status</div>
</div></td>
</tr>
</tbody></table>
</div>
</div>`;
}

function buildFeedbackPrintFooterHtml(memberId, printSetup) {
  const generatedBy = Number(printSetup?.generated_by) === 1 && memberId
    ? `<p id="generated_by">Generated by ${escapeHtml(memberId)} on ${escapeHtml(formatFeedbackGeneratedAt(new Date()))}</p>`
    : '';
  return `<div id="printingFooter" style="display:none;">
<div id="printFooterpanel">
${generatedBy}
<table class="footer_table" border="0" cellpadding="0" cellspacing="0" width="100%"><tbody>
<tr>
<td nowrap valign="top" width="90%"><p class="footer_sign_note"></p></td>
<td height="40" align="right" valign="top" width="10%"><p id="print_page_no"></p></td>
</tr>
</tbody></table>
</div>
</div>`;
}

/** Build course rows from feedback_subject.course_id keys (e.g. 1___2019-2020___2). */
async function buildCourseListFromFeedback(feedbackId) {
  const selectedCourses = await prisma.$queryRawUnsafe(
    `SELECT DISTINCT course_id FROM feedback_subject WHERE del = 1 AND f_id = '${escapeSql(String(feedbackId))}'`,
  );

  const parsed = [];
  const courseIdSet = new Set();
  for (const row of selectedCourses) {
    const cidStr = String(row.course_id || '').trim();
    const parts = cidStr.split('___');
    if (parts.length < 3) continue;
    const [courseIdStr, academicYear, currentYearStr] = parts;
    const courseId = Number(courseIdStr);
    const currentYear = Number(currentYearStr);
    if (!courseId || !academicYear || !currentYear) continue;
    courseIdSet.add(courseId);
    parsed.push({ courseId, academicYear, currentYear, cidStr });
  }

  if (!parsed.length) return [];

  const courseIdsSql = [...courseIdSet].map((id) => `'${escapeSql(String(id))}'`).join(',');
  const courseRows = await prisma.$queryRawUnsafe(
    `SELECT id, course_name, degree_name, department_name
     FROM basic_setup_course_tb WHERE del = 1 AND id IN (${courseIdsSql})`,
  );
  const courseById = new Map(courseRows.map((c) => [Number(c.id), c]));

  const courseList = [];
  for (const item of parsed) {
    const course = courseById.get(item.courseId);
    if (!course) continue;
    let dept = String(course.department_name || '').trim();
    if (dept && dept !== '-') dept = ` - ${dept}`;
    else dept = '';
    courseList.push({
      ...item,
      label: `${convertNYear(item.currentYear, course.course_name)} Year ${course.degree_name}${dept}`,
    });
  }

  return courseList.sort((a, b) => a.label.localeCompare(b.label));
}

async function loadSubjectStaffPairs(feedbackId) {
  const rows = await prisma.$queryRawUnsafe(
    `SELECT C.course_id AS cid_str, B.id AS subject_id, C.staff_id
     FROM feedback_subject AS C
     INNER JOIN basic_subject_tt_tb AS B ON B.id = C.subject_id AND B.del = 1
     INNER JOIN basic_setup_subject_tb AS A ON A.id = B.rid AND A.del = 1
     WHERE C.del = 1 AND C.f_id = '${escapeSql(String(feedbackId))}' AND C.staff_id != ''
     ORDER BY B.subject_category ASC, A.subject_order ASC`,
  );

  const byCourse = new Map();
  for (const row of rows) {
    const cidStr = String(row.cid_str);
    if (!byCourse.has(cidStr)) byCourse.set(cidStr, []);
    const staffList = String(row.staff_id || '').split(',').map((s) => s.trim()).filter(Boolean);
    for (const staffId of staffList) {
      byCourse.get(cidStr).push({
        subjectId: String(row.subject_id),
        staffId,
      });
    }
  }
  return byCourse;
}

async function loadFeedbackFillIndex(feedbackId) {
  const rows = await prisma.$queryRawUnsafe(
    `SELECT course_id, subject_id, staff_id, student_id
     FROM feedback_tb WHERE del = 1 AND feedback_id = '${escapeSql(String(feedbackId))}'`,
  );

  const index = new Map();
  for (const row of rows) {
    const key = `${row.course_id}|${row.subject_id}|${row.staff_id}`;
    if (!index.has(key)) index.set(key, new Set());
    index.get(key).add(String(row.student_id));
  }
  return index;
}

async function loadStudentRegisters(cd, currentDate) {
  const stuRow = await prisma.$queryRawUnsafe(
    `SELECT GROUP_CONCAT(A.register_no SEPARATOR ',') AS regs
     FROM student_profile_tb AS A
     INNER JOIN student_academic_tb AS B ON A.id = B.s_id
     WHERE A.del = 1 AND A.course_id = '${escapeSql(String(cd.courseId))}'
       AND (CAST(A.releaving_date AS CHAR) LIKE '0000-00-00%' OR A.releaving_date > '${escapeSql(currentDate)}')
       AND B.del = 1 AND B.academic_year = '${escapeSql(cd.academicYear)}'
       AND B.current_year = '${escapeSql(String(cd.currentYear))}'`,
  );
  return String(stuRow[0]?.regs || '').split(',').filter(Boolean);
}

function computeFillStats(studentList, subjectStaffPairs, fillIndex, cidStr) {
  const totalSubCount = subjectStaffPairs.length;
  const studentFillStatus = {};

  for (const pair of subjectStaffPairs) {
    const key = `${cidStr}|${pair.subjectId}|${pair.staffId}`;
    const students = fillIndex.get(key);
    if (!students) continue;
    for (const stuid of students) {
      if (!studentFillStatus[stuid]) studentFillStatus[stuid] = {};
      studentFillStatus[stuid][pair.staffId] = pair.staffId;
    }
  }

  let filled = 0;
  let unfilled = 0;
  for (const stuid of studentList) {
    if (Object.keys(studentFillStatus[stuid] || {}).length === totalSubCount) filled += 1;
    else unfilled += 1;
  }

  return { filled, unfilled, total: filled + unfilled };
}

function findFeedbackOption(options, feedbackId) {
  return options.find((f) => Number(f.id) === feedbackId) || null;
}

export async function loadFeedbackDashboardReport(memberId, fields = {}, audit = {}) {
  const feedbackOptions = await loadFeedbackOptions('all');
  const feedbackId = Number(fields.category) || 0;
  const generate = Boolean(fields.generate || fields.Submit === 'Generate');
  let html = '';
  let selectedFeedback = null;

  if (feedbackId) {
    selectedFeedback = findFeedbackOption(feedbackOptions, feedbackId);
  }

  if (generate && selectedFeedback) {
    const currentDate = new Date().toISOString().slice(0, 10);
    const [courseList, subjectStaffByCourse, fillIndex] = await Promise.all([
      buildCourseListFromFeedback(feedbackId),
      loadSubjectStaffPairs(feedbackId),
      loadFeedbackFillIndex(feedbackId),
    ]);

    const studentLists = await Promise.all(
      courseList.map((cd) => loadStudentRegisters(cd, currentDate)),
    );

    let body = '';
    courseList.forEach((cd, i) => {
      const subjectStaffPairs = subjectStaffByCourse.get(cd.cidStr) || [];
      const studentList = studentLists[i];
      const { filled, unfilled, total } = computeFillStats(
        studentList,
        subjectStaffPairs,
        fillIndex,
        cd.cidStr,
      );

      body += `<tr>
<td height="30">${escapeHtml(cd.label)}</td>
<td align="right">${total}</td>
<td align="right">${filled}</td>
<td align="right">${unfilled}</td>
</tr>`;
    });

    if (body) {
      const [bannerUrl, printSetup] = await Promise.all([
        loadBannerImageUrl(),
        loadPrintSetup(FEEDBACK_PRINT_SETUP_ID),
      ]);
      const signatureHtml = Number(printSetup.signature) === 1
        ? await loadPrintSignatureHtml(FEEDBACK_PRINT_SETUP_ID)
        : '';
      const tableHtml = `<div id="form_details_panel">
<table class="table table-bordered feedback-dashboard-report-table" cellpadding="5" cellspacing="0" width="100%">
<thead>
<tr>
<th width="200" height="30">Course</th>
<th width="50">#T</th>
<th width="50">Completed</th>
<th width="50">Pending</th>
</tr>
</thead>
<tbody>${body}</tbody>
</table>${signatureHtml ? `<br><br>${signatureHtml}` : ''}
</div>`;
      html = `${buildFeedbackPrintHeaderHtml(printSetup.title || 'Feedback Analysis', selectedFeedback.title, bannerUrl)}${tableHtml}${buildFeedbackPrintFooterHtml(memberId, printSetup)}`;
    } else {
      html = `<div id="form_details_panel"><p class="text-muted mb-0">No feedback course mapping found for <strong>${escapeHtml(selectedFeedback.title)}</strong>.</p></div>`;
    }
  }

  await logAcademicSetup(PAGE, generate ? 'Generate' : 'View', 'Successful', String(feedbackId), memberId, audit);
  return {
    feedbackOptions,
    feedbackId: feedbackId || '',
    selectedFeedback: selectedFeedback ? {
      id: selectedFeedback.id,
      title: selectedFeedback.title,
      fromDate: formatDateTime(selectedFeedback.fromDate),
      toDate: formatDateTime(selectedFeedback.toDate),
    } : null,
    html,
  };
}

export async function saveFeedbackDashboardReport(memberId, fields = {}, audit = {}) {
  return loadFeedbackDashboardReport(memberId, fields, audit);
}
