import { prisma } from '../../../../config/prisma.js';
import { escapeSql } from '../../../../utils/sqlSafe.js';
import { logAcademicSetup } from '../../setup/setupAudit.js';
import {
  buildPeriodCompletionReport,
  defaultDateRange,
  escapeHtml,
  parseInputDate,
} from './reportShared.js';

const PAGE = 'staff_period_completed.php';

const STAFF_PERIOD_COLUMNS = [
  { label: 'S.No', render: (_r, i) => i + 1 },
  { label: 'Course', key: 'courseLabel' },
  { label: 'Subject', key: 'subjectName' },
  { label: 'Type', key: 'subjectType' },
  { label: 'Assigned Period', key: 'allocated', align: 'right' },
  { label: 'Actual Period', key: 'attended', align: 'right' },
  { label: 'Missed Period', key: 'missed', align: 'right' },
  {
    label: 'Reason',
    render: (r) => `OD : ${r.od} Period<br>AL : ${r.al} Period<br>UL : ${r.ul} period`,
  },
  { label: 'Alternate', key: 'alternate' },
];

function formatStaffPeriodGeneratedAt(d = new Date()) {
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  const timePart = d.toLocaleString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  }).toLowerCase();
  return `${dd}-${mm}-${yyyy} at ${timePart}`;
}

async function loadBannerImageUrl() {
  const rows = await prisma.$queryRawUnsafe(
    'SELECT banner_image FROM basic_banner_tb WHERE del = 1 AND id = 1 LIMIT 1',
  );
  const image = rows[0]?.banner_image;
  return image ? `/legacy/img/global_images/${encodeURIComponent(image)}` : '';
}

function buildStaffPeriodPrintHeaderHtml(reportTitle, dateRange, bannerUrl) {
  const logo = bannerUrl ? `<img src="${escapeHtml(bannerUrl)}" alt="" />` : '';
  return `<div id="printingHeader" style="display:none;">
<div id="printHeaderpanel" class="first-page">
<table class="header_table" border="0" cellpadding="0" cellspacing="0" width="100%"><tbody>
<tr><td align="center" height="5" colspan="2"><small>omsakthi</small></td></tr>
<tr>
<td height="70" valign="middle" width="30%">${logo}</td>
<td nowrap align="right" valign="top" width="70%"><div class="promote_card">
<p class="pc_title title">${escapeHtml(reportTitle)}</p>
<p class="pc_sub-title sub-title">${escapeHtml(dateRange)}</p>
</div></td>
</tr>
</tbody></table>
</div>
</div>`;
}

function buildStaffPeriodGeneratedByHtml(memberId) {
  if (!memberId) return '';
  return `<p id="generated_by" class="staff-period-generated-by">Generated by ${escapeHtml(memberId)} on ${escapeHtml(formatStaffPeriodGeneratedAt(new Date()))}</p>`;
}

function buildStaffPeriodLegacyTable(title, rows, totals, columns) {
  let body = `<h4>${escapeHtml(title)}</h4>
<table border="0" cellpadding="5" cellspacing="0" class="table-bordered staff-period-report-table">
<thead>
<tr>
<th height="20" width="50">S.No</th>
<th width="200" nowrap>Course</th>
<th width="150">Subject</th>
<th width="80">Type</th>
<th width="80">Assigned Period</th>
<th width="80">Actual Period</th>
<th width="80">Missed Period</th>
<th width="150">Reason</th>
<th width="350">Alternate</th>
</tr>
</thead>
<tbody>`;
  rows.forEach((row, idx) => {
    body += '<tr>';
    for (const col of columns) {
      const val = col.render ? col.render(row, idx) : row[col.key];
      const align = col.align ? ` align="${col.align}"` : '';
      body += `<td valign="top"${align}>${val ?? ''}</td>`;
    }
    body += '</tr>';
  });
  if (!rows.length) {
    body += `<tr><td colspan="${columns.length}" align="center" class="text-muted" style="padding:12px;">No records found for the selected staff and date range.</td></tr>`;
  }
  body += '</tbody>';
  if (rows.length) {
    body += `<tfoot><tr>
<th height="30" valign="top" colspan="4" class="text-right">Total</th>
<th valign="top" class="text-right">${totals.total}</th>
<th valign="top" class="text-right">${totals.attend}</th>
<th valign="top" class="text-right">${totals.unattend}</th>
<th valign="top" nowrap></th>
<th valign="top" nowrap></th>
</tr></tfoot>`;
  }
  body += '</table>';
  return body;
}

async function loadStaffSummary(staffPk) {
  const rows = await prisma.$queryRawUnsafe(
    `SELECT id, staff_id, staff_title, staff_name, staff_initial
     FROM staff_profile_tb WHERE del = 1 AND id = ${Number(staffPk)} LIMIT 1`,
  );
  return rows[0] || null;
}

export async function loadStaffPeriodCompletedReport(memberId, fields = {}, audit = {}) {
  const defaults = defaultDateRange();
  const fromDate = fields.from_date || defaults.fromDate;
  const toDate = fields.to_date || defaults.toDate;
  const staffId = Number(fields.staff_id) || 0;
  const generate = Boolean(fields.generate || fields.Submit === 'Generate');
  let html = '';
  let staffOptions = [];

  const ttStaff = await prisma.$queryRawUnsafe(
    `SELECT GROUP_CONCAT(DISTINCT staff_id SEPARATOR ',') AS ids FROM timetable_tb WHERE del = 1 AND staff_id != ''`,
  );
  const idSet = new Set();
  for (const part of String(ttStaff[0]?.ids || '').split(',')) {
    for (const id of part.split(',')) {
      const trimmed = id.trim();
      if (trimmed) idSet.add(trimmed);
    }
  }
  if (idSet.size) {
    const idList = [...idSet].map((id) => `'${escapeSql(id)}'`).join(',');
    const rows = await prisma.$queryRawUnsafe(
      `SELECT id, staff_id, staff_title, staff_name, staff_initial FROM staff_profile_tb
       WHERE del = 1 AND (CAST(releaving_date AS CHAR) LIKE '0000-00-00%' OR releaving_date >= CURDATE())
         AND id IN (${idList}) ORDER BY staff_id ASC`,
    );
    staffOptions = rows.map((r) => ({
      value: String(r.id),
      label: `${r.staff_id} | ${r.staff_title ? `${r.staff_title}. ` : ''}${r.staff_name || ''} ${r.staff_initial || ''}`.trim(),
    }));
  }

  if (generate && staffId) {
    const staff = await loadStaffSummary(staffId);
    const fromIso = parseInputDate(fromDate);
    const toIso = parseInputDate(toDate);
    const { rows, totals } = await buildPeriodCompletionReport({
      fromDate,
      toDate,
      dedupeSubjects: true,
      whereExtra: fromIso && toIso ? `AND (${String(staffId).split(',').map((s) => `(A.staff_id = '${escapeSql(s.trim())}' OR A.staff_id LIKE '${escapeSql(s.trim())},%' OR A.staff_id LIKE '%,${escapeSql(s.trim())}' OR A.staff_id LIKE '%,${escapeSql(s.trim())},%')`).join(' OR ')})` : '',
    });

    const title = staff
      ? `${staff.staff_title ? `${staff.staff_title}. ` : ''}${staff.staff_name || ''} ${staff.staff_initial || ''}`.trim()
      : 'Staff';
    const table = buildStaffPeriodLegacyTable(title, rows, totals, STAFF_PERIOD_COLUMNS);
    const bannerUrl = await loadBannerImageUrl();
    const dateRange = `${fromDate} to ${toDate}`;
    const panelHtml = `<div id="form_details_panel">${table}${buildStaffPeriodGeneratedByHtml(memberId)}</div>`;
    html = `${buildStaffPeriodPrintHeaderHtml('Staff Period Completed', dateRange, bannerUrl)}${panelHtml}`;
  }

  await logAcademicSetup(PAGE, generate ? 'Generate' : 'View', 'Successful', String(staffId), memberId, audit);
  return { staffOptions, staffId: staffId || '', fromDate, toDate, html };
}

export async function saveStaffPeriodCompletedReport(memberId, fields = {}, audit = {}) {
  return loadStaffPeriodCompletedReport(memberId, fields, audit);
}
