import { prisma } from '../../../../config/prisma.js';
import { escapeSql } from '../../../../utils/sqlSafe.js';
import { convertNYear } from '../../../fees/feeHelpers.js';
import { logAcademicSetup } from '../../setup/setupAudit.js';
import { buildSubjectTimingCourseOptions } from '../../academicSetupShared.js';
import {
  escapeHtml,
  getCourseById,
  loadTimetableCategoryMap,
  minutesToHours,
  parseCourseIdYearKey,
  parseInputDate,
  wrapReportPanel,
} from './reportShared.js';

const PAGE = 'subject_timing.php';
const TIMETABLE_TABLES = ['timetable_tb_new', 'timetable_tb'];
const DAY_NAMES = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

function formatSubjectTimingGeneratedAt(d = new Date()) {
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  const timePart = d.toLocaleString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  }).toLowerCase();
  return `${dd}-${mm}-${yyyy} at ${timePart}`;
}

async function loadBannerImageUrl() {
  const rows = await prisma.$queryRawUnsafe(
    'SELECT banner_image FROM basic_banner_tb WHERE del = 1 AND id = 1 LIMIT 1',
  );
  const image = rows[0]?.banner_image;
  return image ? `/legacy/img/global_images/${encodeURIComponent(image)}` : '';
}

function buildSubjectTimingPrintHeaderHtml(reportTitle, bannerUrl) {
  const logo = bannerUrl ? `<img src="${escapeHtml(bannerUrl)}" alt="" />` : '';
  return `<div id="printingHeader" style="display:none;">
<div id="printHeaderpanel" class="first-page">
<table class="header_table" border="0" cellpadding="0" cellspacing="0" width="100%"><tbody>
<tr><td align="center" height="5" colspan="2"><small>omsakthi</small></td></tr>
<tr>
<td height="70" valign="middle" width="30%">${logo}</td>
<td nowrap align="right" valign="top" width="70%"><div class="promote_card">
<p class="pc_title title">${escapeHtml(reportTitle)}</p>
</div></td>
</tr>
</tbody></table>
</div>
</div>`;
}

function buildSubjectTimingGeneratedByHtml(memberId) {
  if (!memberId) return '';
  return `<p id="generated_by" class="subject-timing-generated-by">Generated by ${escapeHtml(memberId)} on ${escapeHtml(formatSubjectTimingGeneratedAt(new Date()))}</p>`;
}

async function resolveTimetableTable(courseId, academicYear, semester, academicType) {
  const cid = escapeSql(String(courseId));
  const year = escapeSql(academicYear);
  const sem = escapeSql(String(semester));
  const type = escapeSql(academicType);
  for (const table of TIMETABLE_TABLES) {
    const rows = await prisma.$queryRawUnsafe(
      `SELECT id FROM ${table}
       WHERE del = 1 AND academic_year = '${year}' AND course_id = '${cid}'
         AND current_year = '${sem}' AND academic_type = '${type}'
         AND CAST(from_date AS CHAR) NOT LIKE '0000-00-00%'
       LIMIT 1`,
    );
    if (rows.length) return table;
  }
  return 'timetable_tb_new';
}

async function loadTimetableData(tableName, courseId, academicYear, semester, academicType) {
  const cid = escapeSql(String(courseId));
  const year = escapeSql(academicYear);
  const sem = escapeSql(String(semester));
  const type = escapeSql(academicType);
  const rows = await prisma.$queryRawUnsafe(
    `SELECT subject_id, t_day, period,
      IF(CAST(from_date AS CHAR) LIKE '0000-00-00%', NULL, from_date) AS from_date,
      IF(CAST(to_date AS CHAR) LIKE '0000-00-00%', NULL, to_date) AS to_date
     FROM ${tableName}
     WHERE del = 1 AND course_id = '${cid}' AND academic_year = '${year}'
       AND current_year = '${sem}' AND academic_type = '${type}'
       AND t_day != '' AND period != ''`,
  );

  let fromDate = null;
  let toDate = null;
  let fromTs = Infinity;
  let toTs = -Infinity;
  for (const row of rows) {
    if (row.from_date && !String(row.from_date).startsWith('0000')) {
      const ts = new Date(row.from_date).getTime();
      if (ts < fromTs) {
        fromTs = ts;
        fromDate = row.from_date;
      }
    }
    if (row.to_date && !String(row.to_date).startsWith('0000')) {
      const ts = new Date(row.to_date).getTime();
      if (ts > toTs) {
        toTs = ts;
        toDate = row.to_date;
      }
    }
  }
  return { rows, fromDate, toDate };
}

async function loadPeriodMinutes(courseName, semester, academicType) {
  const rows = await prisma.$queryRawUnsafe(
    `SELECT DISTINCT p_days, period_no,
       CAST(from_time AS CHAR) AS from_time, CAST(to_time AS CHAR) AS to_time
     FROM period_set_up
     WHERE del != 0 AND period_no != 'Break' AND course_name = '${escapeSql(courseName)}'
       AND academic_year = '${escapeSql(String(semester))}' AND academic_type = '${escapeSql(academicType)}'
     ORDER BY period_no+0 ASC`,
  );
  const map = {};
  for (const row of rows) {
    const day = String(row.p_days || '').toLowerCase();
    const ft = String(row.from_time || '').split(':');
    const tt = String(row.to_time || '').split(':');
    const fromMin = (Number(ft[0]) * 60) + Number(ft[1] || 0);
    const toMin = (Number(tt[0]) * 60) + Number(tt[1] || 0);
    if (!map[day]) map[day] = {};
    map[day][row.period_no] = toMin - fromMin;
  }
  return map;
}

async function buildAcademicDates(fromDate, toDate, courseName) {
  const fromStr = new Date(fromDate).toISOString().slice(0, 10);
  const toStr = new Date(toDate).toISOString().slice(0, 10);
  const calRows = await prisma.$queryRawUnsafe(
    `SELECT CAST(academic_date AS CHAR) AS academic_date, academic_events, course_type
     FROM academic_calender_tb
     WHERE del = 1 AND academic_date >= '${escapeSql(fromStr)}' AND academic_date <= '${escapeSql(toStr)}'`,
  );
  const calMap = Object.fromEntries(
    calRows.map((row) => [String(row.academic_date).slice(0, 10), row]),
  );
  const academicDates = [];
  for (let m = new Date(fromDate).getTime(); m <= new Date(toDate).getTime(); m += 86400000) {
    const curDate = new Date(m).toISOString().slice(0, 10);
    const cal = calMap[curDate];
    const ev = String(cal?.academic_events || '').toLowerCase().slice(0, 7);
    const classList = String(cal?.course_type || '').split(',,,');
    const classContain = !cal?.course_type || classList.includes(courseName);
    if ((ev === 'working' && classContain) || (ev === 'holiday' && !classContain) || !cal) {
      academicDates.push(m);
    }
  }
  return academicDates;
}

function buildAcademicDatesByWeekday(academicDates) {
  const byDay = {};
  for (const m of academicDates) {
    const day = DAY_NAMES[new Date(m).getDay()];
    if (!byDay[day]) byDay[day] = [];
    byDay[day].push(m);
  }
  return byDay;
}

function buildSubjectHoursIndex(timetableRows, academicDatesByDay, periodDetails, fromDate, toDate) {
  const index = new Map();
  for (const row of timetableRows) {
    let fDate = row.from_date;
    let tDate = row.to_date;
    if (!fDate || String(fDate).startsWith('0000')) fDate = fromDate;
    if (!tDate || String(tDate).startsWith('0000')) tDate = toDate;
    if (!fDate || !tDate) continue;

    const fTs = new Date(fDate).getTime();
    const tTs = new Date(tDate).getTime();
    const tDay = String(row.t_day).toLowerCase();
    const periodMins = periodDetails[tDay]?.[row.period] || 0;
    if (!periodMins) continue;

    const matchingDates = (academicDatesByDay[tDay] || []).filter((m) => m >= fTs && m <= tTs);
    if (!matchingDates.length) continue;

    const subjectId = String(row.subject_id);
    index.set(subjectId, (index.get(subjectId) || 0) + (matchingDates.length * periodMins));
  }
  return index;
}

async function loadAllSubjectTtRows(subjectRowIds) {
  const ids = [...new Set(subjectRowIds.map(Number).filter(Boolean))];
  if (!ids.length) return new Map();
  const idsSql = ids.join(',');
  const rows = await prisma.$queryRawUnsafe(
    `SELECT id, rid, subject_id, subject_name, subject_category, req_hours
     FROM basic_subject_tt_tb
     WHERE del = 1 AND rid IN (${idsSql})
     ORDER BY rid ASC, id ASC`,
  );
  const byRid = new Map();
  for (const row of rows) {
    const key = Number(row.rid);
    if (!byRid.has(key)) byRid.set(key, []);
    byRid.get(key).push(row);
  }
  return byRid;
}

async function loadSubjects(academicYear, courseId, semester) {
  return prisma.$queryRawUnsafe(
    `SELECT id, subject_id, subject_name, subject_category, subject_order
     FROM basic_setup_subject_tb
     WHERE del = 1 AND academic_year = '${escapeSql(academicYear)}'
       AND course_id = ${Number(courseId)} AND semester_no = ${Number(semester)}
     ORDER BY subject_order ASC`,
  );
}

function subjectMinutes(hoursIndex, subjectId) {
  return hoursIndex.get(String(subjectId)) || 0;
}

export async function loadSubjectTimingReport(memberId, fields = {}, audit = {}) {
  const courseYearOptions = await buildSubjectTimingCourseOptions();
  const selection = parseCourseIdYearKey(fields.course_name);
  const semester = Number(fields.semester_name) || 1;
  const generate = Boolean(fields.generate || fields.Submit === 'Go');
  let html = '';
  let course = null;

  if (selection) {
    course = await getCourseById(selection.courseId);
  }

  if (generate && selection && course) {
    const [subjects, catMap, tableName] = await Promise.all([
      loadSubjects(selection.academicYear, selection.courseId, semester),
      loadTimetableCategoryMap(),
      resolveTimetableTable(
        selection.courseId,
        selection.academicYear,
        semester,
        selection.academicType,
      ),
    ]);

    if (!subjects.length) {
      html = wrapReportPanel('<p class="text-muted">No subjects found for this course and semester.</p>');
    } else {
      const [timetableData, periodDetails, ttRowsByRid] = await Promise.all([
        loadTimetableData(
          tableName,
          selection.courseId,
          selection.academicYear,
          semester,
          selection.academicType,
        ),
        loadPeriodMinutes(course.course_name || '', semester, selection.academicType),
        loadAllSubjectTtRows(subjects.map((sub) => sub.id)),
      ]);
      const { rows: timetableRows, fromDate, toDate } = timetableData;
      const academicDates = (fromDate && toDate)
        ? await buildAcademicDates(fromDate, toDate, course.course_name || '')
        : [];
      const hoursIndex = buildSubjectHoursIndex(
        timetableRows,
        buildAcademicDatesByWeekday(academicDates),
        periodDetails,
        fromDate,
        toDate,
      );

      let body = '';
      const totals = { lec: 0, lab: 0, cli: 0, tot: 0 };
      let reqLec = 0;
      let reqLab = 0;
      let reqCli = 0;
      let idx = 0;

      for (const sub of subjects) {
        const ttRows = ttRowsByRid.get(Number(sub.id)) || [];
        if (!ttRows.length) continue;
        idx += 1;

        const byCat = { lecture: {}, lab: {}, clinical: {} };
        const reqByCat = { lecture: {}, lab: {}, clinical: {} };
        const names = {};
        for (const tt of ttRows) {
          const cat = String(catMap[String(tt.subject_category)] || '').toLowerCase();
          const norm = String(tt.subject_name || '').toLowerCase().replace(/[\s,\-_\(\)\[\]]/g, '') || 'tmp';
          names[norm] = tt.subject_name;
          if (cat === 'lecture') {
            byCat.lecture[norm] = tt.id;
            reqByCat.lecture[norm] = tt.req_hours;
          } else if (cat === 'lab') {
            byCat.lab[norm] = tt.id;
            reqByCat.lab[norm] = tt.req_hours;
          } else if (cat === 'clinical') {
            byCat.clinical[norm] = tt.id;
            reqByCat.clinical[norm] = tt.req_hours;
          }
        }

        const multi = Object.keys(byCat.lecture).length > 1
          || Object.keys(byCat.clinical).length > 1
          || Object.keys(byCat.lab).length > 1;
        if (multi) {
          body += `<tr><td>${idx}</td><td><strong>${escapeHtml(sub.subject_name)}</strong></td><td colspan="7"></td></tr>`;
          for (const [norm, name] of Object.entries(names)) {
            const lec = byCat.lecture[norm]
              ? subjectMinutes(hoursIndex, byCat.lecture[norm]) : 0;
            const lab = byCat.lab[norm]
              ? subjectMinutes(hoursIndex, byCat.lab[norm]) : 0;
            const cli = byCat.clinical[norm]
              ? subjectMinutes(hoursIndex, byCat.clinical[norm]) : 0;
            const tot = lec + lab + cli;
            totals.lec += lec;
            totals.lab += lab;
            totals.cli += cli;
            totals.tot += tot;
            body += `<tr><td></td><td>${escapeHtml(name)}</td><td></td><td class="text-end">${minutesToHours(lec)}</td><td></td><td class="text-end">${minutesToHours(lab)}</td><td></td><td class="text-end">${minutesToHours(cli)}</td><td class="text-end">${minutesToHours(tot)}</td></tr>`;
          }
        } else {
          let lec = 0;
          let lab = 0;
          let cli = 0;
          let lecReq = 0;
          let labReq = 0;
          let cliReq = 0;
          for (const [norm, sid] of Object.entries(byCat.lecture)) {
            lec = subjectMinutes(hoursIndex, sid);
            lecReq = reqByCat.lecture[norm] || 0;
          }
          for (const [norm, sid] of Object.entries(byCat.lab)) {
            lab = subjectMinutes(hoursIndex, sid);
            labReq = reqByCat.lab[norm] || 0;
          }
          for (const [norm, sid] of Object.entries(byCat.clinical)) {
            cli = subjectMinutes(hoursIndex, sid) / 8;
            cliReq = reqByCat.clinical[norm] || 0;
          }
          const tot = lec + lab + cli;
          totals.lec += lec;
          totals.lab += lab;
          totals.cli += cli;
          totals.tot += tot;
          reqLec += Number(lecReq) || 0;
          reqLab += Number(labReq) || 0;
          reqCli += Number(cliReq) || 0;
          body += `<tr><td>${idx}</td><td>${escapeHtml(sub.subject_name)}</td>
            <td class="text-center">${escapeHtml(lecReq)}</td><td class="text-center">${minutesToHours(lec)}</td>
            <td class="text-center">${escapeHtml(labReq)}</td><td class="text-center">${minutesToHours(lab)}</td>
            <td class="text-center">${escapeHtml(cliReq)}</td><td class="text-center">${minutesToHours(cli)}</td>
            <td class="text-center">${minutesToHours(tot)}</td></tr>`;
        }
      }

      if (!body) {
        html = wrapReportPanel('<p class="text-muted">No timetable subjects found for this selection.</p>');
      } else {
        body += `<tr><td></td><td>Total</td>
          <td>${reqLec}</td><td class="text-end">${minutesToHours(totals.lec)}</td>
          <td>${reqLab}</td><td class="text-end">${minutesToHours(totals.lab)}</td>
          <td>${reqCli}</td><td class="text-end">${minutesToHours(totals.cli)}</td>
          <td class="text-end">${minutesToHours(totals.tot)}</td></tr>`;

        const fromDisp = fromDate && parseInputDate(fromDate)
          ? new Date(fromDate).toLocaleDateString('en-GB') : '';
        const toDisp = toDate && parseInputDate(toDate)
          ? new Date(toDate).toLocaleDateString('en-GB') : '';
        const dateLabel = fromDisp && toDisp ? `${fromDisp} to ${toDisp}` : 'No timetable date range found';

        let deptLabel = String(course.department_name || '').trim();
        if (deptLabel && deptLabel !== '-') deptLabel = ` - ${deptLabel}`;
        else deptLabel = '';
        const degreeLabel = `${course.degree_name || ''}${deptLabel}`;

        const metaTable = `<table border="0" cellpadding="0" cellspacing="0" width="100%" class="table subject-timing-meta-table">
<tr><td height="35"><strong>Course</strong></td><td width="70%">${escapeHtml(convertNYear(semester, course.course_name || 'U.G'))} year | ${escapeHtml(degreeLabel)}</td></tr>
<tr><td height="35" width="10%" nowrap><strong>Academic Year</strong></td><td>${escapeHtml(selection.academicYear)}</td></tr>
<tr><td height="35" width="10%" nowrap><strong>Date</strong></td><td>${escapeHtml(dateLabel)}</td></tr>
</table>`;

        const dataTable = `<table width="100%" border="0" cellspacing="0" cellpadding="5" class="table table-bordered subject-timing-report-table" style="margin:0px;">
<thead>
<tr bgcolor="#F4F4F4">
<th width="10%" nowrap height="30" rowspan="2">#</th>
<th width="30%" nowrap rowspan="2">Subject Name</th>
<th width="15%" nowrap align="middle" colspan="2">Lecture Hours</th>
<th width="15%" nowrap colspan="2">Practical Hours</th>
<th width="15%" nowrap colspan="2">Clinical Hours</th>
<th width="15%" nowrap rowspan="2">Total Hours</th>
</tr>
<tr bgcolor="#f4f4f4">
<th width="10%" nowrap>Req.</th><th width="10%" nowrap>Actual</th>
<th width="10%" nowrap>Req.</th><th width="10%" nowrap>Actual</th>
<th width="10%" nowrap>Req.</th><th width="10%" nowrap>Actual</th>
</tr>
</thead>
<tbody>${body}</tbody>
</table>`;

        const bannerUrl = await loadBannerImageUrl();
        const generatedByHtml = buildSubjectTimingGeneratedByHtml(memberId);
        const panelHtml = `<div id="form_details_panel">${metaTable}${dataTable}${generatedByHtml}</div>`;
        html = `${buildSubjectTimingPrintHeaderHtml('Subject List', bannerUrl)}${panelHtml}`;
      }
    }
  }

  await logAcademicSetup(PAGE, 'View', 'Successful', fields.course_name || '', memberId, audit);
  return {
    courseYearOptions,
    courseYearKey: fields.course_name || '',
    selection,
    semester,
    totalSemester: course ? Number(course.total_semester) || Number(course.course_duration) || 0 : 0,
    html,
  };
}

export async function saveSubjectTimingReport(memberId, fields = {}, audit = {}) {
  return loadSubjectTimingReport(memberId, fields, audit);
}
