export const BRIDGE_LEGACY_PAGES = {
  academic: {
    'subject-master': 'subject_master.php',
    'course-add': 'course_add.php',
    'course-edit': 'course_edit.php',
    'academic-years': 'academic.php',
    'subject-setup': 'subject_setup.php',
    'subject-batch': 'subject_batch.php',
    'academic-calendar': 'academic_calendar.php',
    'subject-schedule': 'subject_schedule.php',
    'subject-unit': 'subject_unit_setup_v2.php',
    'admission-exam': 'academic_admission_setup.php',
    'master-setup': 'master_setup.php',
    'subject-report': 'subject_report.php',
    'timetable-report': 'timetable_class_report.php',
    'batch-timetable-report': 'class_time_table_batch_report.php',
    'tt-config': 'tt_config.php',
  },
  exam: {
    'exam-names': 'exam_name_config.php',
    'exam-setup': 'term_exam_setup.php',
    'mark-entry': 'term_mark_entry.php',
    'exam-batch': 'exam_batch.php',
    'term-report': 'term_report.php',
    'term-statement': 'term_report_statement.php',
    'progress-card': 'term_progress_card.php',
    'mark-sheet': 'term_mark_sheet.php',
    'exam-schedule': 'term_exam_schedule.php',
    'marks-upload': 'term_marks_upload.php',
    'schedule-print': 'term_exam_sch_print.php',
    'invigilator-print': 'term_exam_Inviliga_sch_print.php',
    'report-analysis': 'term_report_analysis.php',
    'omr-config': 'omr_style_config.php',
  },
  admin: {
    'account-add': 'account_add.php',
    'account-edit': 'account_edit.php',
    'access-restriction': 'access.php',
    'dept-auth': 'department_authentication.php',
    'menu-auth': 'authentication_add.php',
    'dashboard-access': 'dashboard_access.php',
    'log-dashboard': 'log_dashboard.php',
    'log-details': 'log_details.php',
  },
  fee: {
    label: 'fee_label_config.php',
    type: 'fee_type_config.php',
    bank: 'fee_bank_config.php',
    fine: 'fee_fine_config.php',
    name: 'fee_name_config.php',
  },
  payroll: {
    dashboard: 'payroll_dashboard.php',
    'individual-report': 'payroll_individual_report.php',
    'individual-bundle': 'payroll_individual_report1.php',
    'consolidated-report': 'payroll_consolidated_report.php',
    'salary-summary': 'salary_summary.php',
    'salary-statement': 'salary_statement.php',
    'individual-setup': 'payroll_individual_setup.php',
    'cron-setup': 'payroll_cron_setup.php',
    'group-report': 'payroll_group_report.php',
    'stipend-report': 'stipend_payroll_report.php',
    'stipend-statement': 'stipend_salary_statement.php',
    'stipend-individual-report': 'stipend_payroll_individual_report1.php',
    'stipend-generate-payroll': 'stipend_generate_payroll.php',
    'stipend-amount-setup': 'stipend_amount_setup.php',
    'stipend-deduction-add': 'stipend_deduction_add.php',
    'stipend-payroll-close': 'stipend_payroll_close.php',
    'stipend-att-report': 'stipend_payroll_att_report.php',
  },
};

export function legacyPageFor(module, screen) {
  return BRIDGE_LEGACY_PAGES[module]?.[screen] || `${screen}.php`;
}
