import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../api/client';
import DashboardLayout from '../../layouts/DashboardLayout';
import { printReportHtml } from '../../utils/printReport';
import '../exam/ExamSetupPage.css';

export default function PayrollDashboard() {
  const [settings, setSettings] = useState(null);
  const [menu, setMenu] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [data, setData] = useState(null);
  const [payrollMonth, setPayrollMonth] = useState('');

  const loadDashboard = useCallback(async (fields = {}) => {
    setBusy(true);
    setError(null);
    try {
      const res = await api.post('/api/payroll/dashboard', { fields });
      setData(res.data);
      setPayrollMonth(res.data.selectedMonth || '');
    } catch (err) {
      setError(err.response?.data?.message || 'Unable to load payroll dashboard');
      setData(null);
    } finally {
      setBusy(false);
    }
  }, []);

  useEffect(() => {
    const init = async () => {
      try {
        const [settingsRes, menuRes] = await Promise.all([
          api.get('/api/settings/basic'),
          api.get('/api/menu'),
        ]);
        setSettings(settingsRes.data);
        setMenu(menuRes.data.menu || []);
        await loadDashboard();
      } catch (err) {
        setError(err.message || 'Unable to initialize payroll dashboard');
      } finally {
        setLoading(false);
      }
    };
    init();
  }, [loadDashboard]);

  const onMonthChange = async (value) => {
    setPayrollMonth(value);
    await loadDashboard({ payroll_month: value });
  };

  if (loading) {
    return <div className="p-4 text-muted">Loading...</div>;
  }

  return (
    <DashboardLayout settings={settings} dashboard={{ title: 'Payroll Dashboard' }} menu={menu}>
      <nav aria-label="breadcrumb">
        <ol className="breadcrumb">
          <li className="breadcrumb-item"><Link to="/dashboard">Home</Link></li>
          <li className="breadcrumb-item"><Link to="/payroll">Payroll</Link></li>
          <li className="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>

      <div className="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
        <div>
          <h3 className="dashboard-title mb-0">Payroll Dashboard</h3>
          <p className="text-muted small mb-0">Native SQL from staff_payroll_tb</p>
        </div>
        <div className="d-flex gap-2">
          {data?.reportHtml && (
            <button type="button" className="btn btn-outline-primary btn-sm" onClick={() => printReportHtml(data.reportHtml)}>
              Print
            </button>
          )}
          <Link to="/payroll" className="btn btn-outline-secondary btn-sm">Back</Link>
        </div>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}
      {busy && <div className="text-muted small mb-2">Loading…</div>}

      <div className="card shadow-sm exam-setup-card mb-3">
        <div className="card-body">
          <div className="row g-3 align-items-end">
            <div className="col-md-4">
              <label className="form-label">Month</label>
              <select className="form-select" value={payrollMonth} onChange={(e) => onMonthChange(e.target.value)}>
                <option value="">-Select Month-</option>
                {(data?.monthOptions || []).map((opt) => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            </div>
            {data?.generatedBy?.user && (
              <div className="col-md-8 text-muted small">
                Generated by {data.generatedBy.user}
                {data.generatedBy.date ? ` on ${data.generatedBy.date}` : ''}
              </div>
            )}
          </div>
        </div>
      </div>

      {data?.reportHtml ? (
        <div className="card shadow-sm">
          <div className="card-body payroll-dashboard-root" dangerouslySetInnerHTML={{ __html: data.reportHtml }} />
        </div>
      ) : (
        payrollMonth && !busy && <p className="text-muted">No payroll summary available for the selected month.</p>
      )}
    </DashboardLayout>
  );
}
