export const PAYROLL_SCREEN_META = {
  'individual-setup': { title: 'Payroll Cover Page', legacy: 'payroll_individual_setup.php' },
  'cron-setup': { title: 'Payroll Cron Email', legacy: 'payroll_cron_setup.php' },
  'payroll-config': { title: 'Payroll Group Setup', legacy: 'staff_payroll_setup.php' },
  'pf-esi-setup': { title: 'PF / ESI Setup', legacy: 'staff_pfesi_setup.php' },
  'salary-add': { title: 'Staff Salary Setup', legacy: 'staff_salary_setup.php' },
  'salary-report': { title: 'Salary Setup Report', legacy: 'staff_salary_report.php' },
  'salary-advance-add': { title: 'Salary Advance Add', legacy: 'salary_advance_add.php' },
  'salary-advance-close': { title: 'Salary Advance Close', legacy: 'salary_advance_edit.php' },
  'salary-arrear-add': { title: 'Salary Arrear Add', legacy: 'salary_arrear_add.php' },
  'salary-arrear-release': { title: 'Salary Arrear Release', legacy: 'salary_arrear_edit.php' },
  'other-deduction': { title: 'Other Deduction', legacy: 'staff_deduction_add.php' },
  'lop-deduction': { title: 'LOP Deduction', legacy: 'staff_lop_deduction.php' },
  'tds-add': { title: 'TDS Entry', legacy: 'staff_tds_add.php' },
  'cheque-payment': { title: 'Cheque Payment', legacy: 'staff_cheque_add.php' },
  'security-deposit-add': { title: 'Security Deposit Add', legacy: 'security_deposit_deduction_add.php' },
  'security-deposit-close': { title: 'Security Deposit Close', legacy: 'security_deposit_deduction_close.php' },
  'payroll-close': { title: 'Payroll Close', legacy: 'payroll_close.php' },
};
