export const EXAM_SCREEN_META = {
  'exam-names': { title: 'Exam Names', legacy: 'exam_name_config.php', hub: 'setup' },
  'exam-setup': { title: 'Exam Setup', legacy: 'term_exam_setup.php', hub: 'setup' },
  'mark-entry': { title: 'Mark Entry', legacy: 'term_mark_entry.php', hub: 'setup' },
  'exam-batch': { title: 'Exam Batch Allocation', legacy: 'exam_batch.php', hub: 'setup' },
  'term-report': { title: 'Term Report', legacy: 'term_report.php', hub: 'reports' },
  'term-statement': { title: 'Result Statement', legacy: 'term_report_statement.php', hub: 'reports' },
  'progress-card': { title: 'Progress Card', legacy: 'term_progress_card.php', hub: 'reports' },
  'mark-sheet': { title: 'Mark Sheet Print', legacy: 'term_mark_sheet.php', hub: 'setup' },
  'exam-schedule': { title: 'Exam Schedule', legacy: 'term_exam_schedule.php', hub: 'setup' },
  'marks-upload': { title: 'OMR Mark Upload', legacy: 'term_marks_upload.php', hub: 'setup' },
  'schedule-print': { title: 'Exam Schedule Print', legacy: 'term_exam_sch_print.php', hub: 'reports' },
  'invigilator-print': { title: 'Invigilator Schedule', legacy: 'term_exam_Inviliga_sch_print.php', hub: 'reports' },
  'report-analysis': { title: 'Term Report Analysis', legacy: 'term_report_analysis.php', hub: 'reports' },
  'omr-config': { title: 'OMR Sheet Layout', legacy: 'omr_style_config.php', hub: 'setup' },
  'exam-nodue': { title: 'No Due Verification', legacy: 'term_exam_nodue.php', hub: 'setup' },
  'exam-examiners': { title: 'Exam Examiners', legacy: 'term_exam_examiners.php', hub: 'setup' },
  'exam-attendance-certificate': { title: 'Exam Attendance Certificate', legacy: 'term_exam_att_certificate.php', hub: 'reports', readOnly: true },
  'examiner-setup': { title: 'Examiner Setup', legacy: 'term_examiner_setup.php', hub: 'setup' },
  'camp-activity-add': { title: 'Camp Activity Add', legacy: 'camp_activity_add.php', hub: 'setup' },
  'camp-activity-edit': { title: 'Camp Activity Edit', legacy: 'camp_activity_edit.php', hub: 'setup' },
  'camp-activity-type': { title: 'Camp Activity Type', legacy: 'camp_activity_type.php', hub: 'setup' },
  'attendance-entry': { title: 'Attendance Entry', legacy: 'term_attendance_entry.php', hub: 'setup' },
  'attendance-report': { title: 'Attendance Report', legacy: 'term_attendance_report.php', hub: 'reports', readOnly: true },
  'sheets-upload': { title: 'Term Sheets Upload', legacy: 'term_sheets_upload.php', hub: 'setup', readOnly: true },
  'sheets-status': { title: 'Term Sheets Status', legacy: 'term_sheets_status.php', hub: 'reports', readOnly: true },
  'mark-sheet-status': { title: 'Mark Sheet Status', legacy: 'term_mark_sheet_status.php', hub: 'reports', readOnly: true },
  'mark-sheet-received': { title: 'Mark Sheet Received', legacy: 'term_mark_sheet_received.php', hub: 'reports', readOnly: true },
  'exam-sms': { title: 'Exam SMS', legacy: 'exam_sms.php', hub: 'setup' },
  'report-analysis-v1': { title: 'Term Report Analysis v1', legacy: 'term_report_analysis_v1.php', hub: 'reports', readOnly: true },
};
