export const ACADEMIC_SCREEN_META = {
  'subject-master': { title: 'Subject Categories', legacy: 'subject_master.php', hub: 'setup' },
  'course-add': { title: 'Add Course', legacy: 'course_add.php', hub: 'setup' },
  'course-edit': { title: 'Edit Course', legacy: 'course_edit.php', hub: 'setup' },
  'academic-years': { title: 'Academic Year Setup', legacy: 'academic.php', hub: 'setup' },
  'subject-setup': { title: 'Subject Setup', legacy: 'subject_setup.php', hub: 'setup' },
  'subject-batch': { title: 'Student Batch Allocation', legacy: 'subject_batch.php', hub: 'setup' },
  'academic-calendar': { title: 'Academic Calendar', legacy: 'academic_calendar.php', hub: 'setup' },
  'subject-schedule': { title: 'Subject Timetable', legacy: 'subject_schedule.php', hub: 'setup' },
  'subject-unit': { title: 'Subject Unit / Chapter', legacy: 'subject_unit_setup_v2.php', hub: 'setup' },
  'admission-exam': { title: 'Admission Exam Mapping', legacy: 'academic_admission_setup.php', hub: 'setup' },
  'master-setup': { title: 'Master Setup', legacy: 'master_setup.php', hub: 'setup' },
  'subject-report': { title: 'Subject Report', legacy: 'subject_report.php', hub: 'reports' },
  'timetable-report': { title: 'Class Timetable Report', legacy: 'timetable_class_report.php', hub: 'reports' },
  'batch-timetable-report': { title: 'Batch Timetable Report', legacy: 'class_time_table_batch_report.php', hub: 'reports' },
  'tt-config': { title: 'Weekly Timetable Grid', legacy: 'tt_config.php', hub: 'setup' },
  // Curriculum — setup
  'batch-color': { title: 'Batch Color', legacy: 'batch_color_setup.php', hub: 'setup' },
  'feedback-topics': { title: 'Feedback Topics', legacy: 'feedback_topic.php', hub: 'setup' },
  'period-setup': { title: 'Period Setup', legacy: 'period_setup.php', hub: 'setup' },
  'internship-schedule': { title: 'Internship Schedule', legacy: 'internship_schedule.php', hub: 'setup' },
  'feedback-config-ug': { title: 'Feedback Setup (UG)', legacy: 'feedback_config.php', hub: 'setup' },
  'feedback-config-pg': { title: 'Feedback Setup (PG)', legacy: 'feedback_config_pg.php', hub: 'setup' },
  'tt-config-v3': { title: 'Weekly Timetable Grid (New)', legacy: 'tt_config_v3.php', hub: 'setup' },
  // Curriculum — reports
  'subject-dashboard': { title: 'Subject Dashboard', legacy: 'subject_dashboard.php', hub: 'reports' },
  'subject-schedule-report': { title: 'Subject Schedule Status', legacy: 'subject_schedule_report.php', hub: 'reports' },
  'subject-timing': { title: 'Subject Timing', legacy: 'subject_timing.php', hub: 'reports' },
  'feedback-dashboard': { title: 'Feedback Status', legacy: 'feedback_dashboard.php', hub: 'reports' },
  'class-timetable': { title: 'Class Timetable', legacy: 'class_time_table.php', hub: 'reports' },
  'class-timetable-v3': { title: 'Class Timetable (New)', legacy: 'class_time_table_v3.php', hub: 'reports' },
  'feedback-report-ug': { title: 'Feedback Report (UG)', legacy: 'feedback_report.php', hub: 'reports' },
  'feedback-report-pg': { title: 'Feedback Report (PG)', legacy: 'feedback_report_pg.php', hub: 'reports' },
  'subject-handle': { title: 'Period Completed (Class)', legacy: 'subject_handle.php', hub: 'reports' },
  'staff-period-completed': { title: 'Period Completed (Staff)', legacy: 'staff_period_completed.php', hub: 'reports' },
  'department-period-completed': { title: 'Period Completed (Dept.)', legacy: 'department_period_completed.php', hub: 'reports' },
  'subject-handle-grid': { title: 'Subject Attendance (Staff)', legacy: 'subject_handle1.php', hub: 'reports' },
};
