/** CSS variable maps for live theme switching (master control). */

export const THEME_STORAGE_KEY = 'cis_theme_v1';
export const DEFAULT_THEME_ID = 'campus-red';
export const DEFAULT_SIDEBAR_MODE = 'dark';

const SIDEBAR_DARK = {
  '--cis-sidebar-bg': '#141014',
  '--cis-sidebar-bg-elevated': '#1f1718',
  '--cis-sidebar-text': 'rgba(255, 255, 255, 0.86)',
  '--cis-sidebar-text-muted': 'rgba(255, 255, 255, 0.52)',
  '--cis-sidebar-hover': 'rgba(255, 255, 255, 0.08)',
  '--cis-sidebar-active-bg': 'var(--cis-primary)',
  '--cis-sidebar-active': '#ffffff',
  '--cis-sidebar-border': 'rgba(255, 255, 255, 0.08)',
  '--cis-sidebar-label': 'rgba(255, 255, 255, 0.38)',
};

const SIDEBAR_LIGHT = {
  '--cis-sidebar-bg': '#ffffff',
  '--cis-sidebar-bg-elevated': '#fafaf8',
  '--cis-sidebar-text': '#3d3835',
  '--cis-sidebar-text-muted': '#6b6560',
  '--cis-sidebar-hover': 'rgba(26, 26, 26, 0.05)',
  '--cis-sidebar-active-bg': 'var(--cis-primary-soft)',
  '--cis-sidebar-active': 'var(--cis-primary)',
  '--cis-sidebar-border': '#e8e4dc',
  '--cis-sidebar-label': '#9c958c',
};

export const SIDEBAR_MODES = {
  dark: SIDEBAR_DARK,
  light: SIDEBAR_LIGHT,
};

export const THEME_PRESETS = {
  'campus-red': {
    id: 'campus-red',
    label: 'Campus Red & Yellow',
    description: 'Dark sidebar · red primary · pale yellow accent',
    swatches: ['#a61a1a', '#f5d15f', '#1f1616', '#fafaf8'],
    defaultSidebar: 'dark',
    vars: {
      '--cis-primary': '#a61a1a',
      '--cis-primary-hover': '#8b1515',
      '--cis-primary-soft': '#fff0ee',
      '--cis-primary-rgb': '166, 26, 26',
      '--cis-accent': '#f5d15f',
      '--cis-accent-hover': '#e6bc3a',
      '--cis-accent-soft': '#fffbeb',
      '--cis-accent-rgb': '245, 209, 95',
      '--cis-peach-soft': '#fff5f2',
      '--cis-bg': '#fafaf8',
      '--cis-bg-subtle': 'hsl(0, 0%, 97%)',
      '--cis-shell-bg': '#f0efec',
      '--cis-border': '#e8e4dc',
      '--cis-border-strong': '#d6d0c4',
      '--bs-primary-rgb': '166, 26, 26',
    },
  },
  'slate-amber': {
    id: 'slate-amber',
    label: 'Slate Blue & Amber',
    description: 'Dark sidebar · slate blue · warm amber accent',
    swatches: ['#334e68', '#f0b429', '#1e293b', '#f8fafc'],
    defaultSidebar: 'dark',
    vars: {
      '--cis-primary': '#334e68',
      '--cis-primary-hover': '#243b53',
      '--cis-primary-soft': '#eef2f7',
      '--cis-primary-rgb': '51, 78, 104',
      '--cis-accent': '#f0b429',
      '--cis-accent-hover': '#de9e0f',
      '--cis-accent-soft': '#fffbeb',
      '--cis-accent-rgb': '240, 180, 41',
      '--cis-peach-soft': '#f0f4f8',
      '--cis-bg': '#f8fafc',
      '--cis-bg-subtle': '#eef2f7',
      '--cis-shell-bg': '#e2e8f0',
      '--cis-border': '#d9e2ec',
      '--cis-border-strong': '#bcccdc',
      '--bs-primary-rgb': '51, 78, 104',
    },
  },
  'forest-teal': {
    id: 'forest-teal',
    label: 'Forest & Teal',
    description: 'Dark sidebar · deep green · soft mint accent',
    swatches: ['#0d5c4b', '#5eead4', '#134e4a', '#f0fdf9'],
    defaultSidebar: 'dark',
    vars: {
      '--cis-primary': '#0d5c4b',
      '--cis-primary-hover': '#0a4a3c',
      '--cis-primary-soft': '#ecfdf5',
      '--cis-primary-rgb': '13, 92, 75',
      '--cis-accent': '#5eead4',
      '--cis-accent-hover': '#2dd4bf',
      '--cis-accent-soft': '#f0fdf9',
      '--cis-accent-rgb': '94, 234, 212',
      '--cis-peach-soft': '#ecfdf5',
      '--cis-bg': '#f7fefc',
      '--cis-bg-subtle': '#ecfdf5',
      '--cis-shell-bg': '#e6f7f2',
      '--cis-border': '#cce8df',
      '--cis-border-strong': '#99d4c4',
      '--bs-primary-rgb': '13, 92, 75',
    },
  },
  'navy-gold': {
    id: 'navy-gold',
    label: 'Navy & Gold',
    description: 'Dark sidebar · navy primary · gold highlights',
    swatches: ['#1e3a5f', '#d4a843', '#0f2744', '#f5f7fa'],
    defaultSidebar: 'dark',
    vars: {
      '--cis-primary': '#1e3a5f',
      '--cis-primary-hover': '#152a45',
      '--cis-primary-soft': '#eef3f9',
      '--cis-primary-rgb': '30, 58, 95',
      '--cis-accent': '#d4a843',
      '--cis-accent-hover': '#b88f2e',
      '--cis-accent-soft': '#fdf8ee',
      '--cis-accent-rgb': '212, 168, 67',
      '--cis-peach-soft': '#f0f4fa',
      '--cis-bg': '#f5f7fa',
      '--cis-bg-subtle': '#eef3f9',
      '--cis-shell-bg': '#e4e9f0',
      '--cis-border': '#d8dee8',
      '--cis-border-strong': '#bcc5d4',
      '--bs-primary-rgb': '30, 58, 95',
    },
  },
  'charcoal-coral': {
    id: 'charcoal-coral',
    label: 'Charcoal & Coral',
    description: 'Dark sidebar · charcoal · coral accent',
    swatches: ['#c2410c', '#fdba74', '#292524', '#fafaf9'],
    defaultSidebar: 'dark',
    vars: {
      '--cis-primary': '#c2410c',
      '--cis-primary-hover': '#9a3412',
      '--cis-primary-soft': '#fff7ed',
      '--cis-primary-rgb': '194, 65, 12',
      '--cis-accent': '#fdba74',
      '--cis-accent-hover': '#fb923c',
      '--cis-accent-soft': '#fff7ed',
      '--cis-accent-rgb': '253, 186, 116',
      '--cis-peach-soft': '#fff7ed',
      '--cis-bg': '#fafaf9',
      '--cis-bg-subtle': '#fff7ed',
      '--cis-shell-bg': '#eceae8',
      '--cis-border': '#e7e5e4',
      '--cis-border-strong': '#d6d3d1',
      '--bs-primary-rgb': '194, 65, 12',
    },
  },
};

export const THEME_PRESET_LIST = Object.values(THEME_PRESETS);
